### ISSUE TITLE
This channel is not responding.

### ISSUE THREAD

**Issue by TheAnalytiker** [chatby/Shahid.bundle#2]
Hello,

i get this massage when i want to open any video

Could you help me, please?

**Comment by chatby** [comment]
delete the previous Shahid.bundle and reinstalled again. if you got the message that you mentioned, just go back on the browser and click again the same show.

**Comment by TheAnalytiker** [comment]
thanks, but it doesn't work

**Comment by chatby** [comment]
does the name of the series show up?

**Comment by chatby** [comment]
Shahid website is blocked if you're not in the middle east and connect to it through web based proxy causes the browsing to be slower. I think that is why you getting the error message, however this bundle still works.

**Comment by TheAnalytiker** [comment]
Oh, okay :+1:  Thanks

**Comment by chatby** [comment]
I made a few changes and I hope it works for you.
